<?php
/**
 * MediOrbit - Database Data Layer Config
 * 12 Distinct Metabolic Conditions Dataset with English and Urdu Localized Values
 */

$metabolic_conditions = [
    [
        'id' => 'organ-strain',
        'title_en' => 'Organ Strain',
        'title_ur' => 'اعضاء پر دباؤ',
        'target_kcal' => 1200,
        'tag' => 'Nephrology & Hepatology',
        'description_en' => 'High metabolic load causing strain on kidney and liver filtration processes, requiring restricted intake to minimize toxic buildup.',
        'description_ur' => 'گردوں اور جگر کے فلٹریشن کے عمل پر زیادہ میٹابولک بوجھ جس کی وجہ سے زہریلے مادوں کے اجتماع کو کم کرنے کے لیے خوراک کو محدود کرنا پڑتا ہے۔',
        'reason_en' => 'Excessive consumption of proteins and heavy fats forces metabolic organs to work over capacity, resulting in cellular exhaustion and structural stress.',
        'reason_ur' => 'پروٹین اور بھاری چربی کا ضرورت سے زیادہ استعمال فلٹریشن کے اعضاء کو ان کی صلاحیت سے زیادہ کام کرنے پر مجبور کرتا ہے، جس سے سیلولر تھکن اور اعضاء پر دباؤ پڑتا ہے۔',
        'avoid_en' => ['High Sodium Foods', 'Refined Sugars', 'Excessive Red Meat', 'Processed Meats'],
        'avoid_ur' => ['زیادہ نمک والی غذائیں', 'ریفائنڈ چینی', 'سرخ گوشت کی زیادتی', 'پروسیسڈ گوشت'],
        'control_en' => ['Limit daily protein intake to 0.8g/kg', 'Establish strict 4-hour fasting windows between meals', 'Maintain hydration with pure water only'],
        'control_ur' => ['روزانہ پروٹین کی مقدار 0.8 گرام فی کلوگرام تک محدود کریں', 'کھانے کے درمیان 4 گھنٹے کا وقفہ برقرار رکھیں', 'صرف صاف پانی پی کر ہائیڈریشن کو برقرار رکھیں']
    ],
    [
        'id' => 'metabolic-stress',
        'title_en' => 'Metabolic Stress',
        'title_ur' => 'میٹابولک تناؤ',
        'target_kcal' => 1300,
        'tag' => 'Endocrinology',
        'description_en' => 'Cellular inflammation caused by continuous over-nutrition, leading to dysregulated insulin response and hormone signaling imbalances.',
        'description_ur' => 'مسلسل ضرورت سے زیادہ غذائیت کی وجہ سے خلیاتی سوزش، جو انسولین کے غیر منظم ردعمل اور ہارمون سگنلنگ کے عدم توازن کا باعث بنتی ہے۔',
        'reason_en' => 'Eating beyond physiological energy demands floods mitochondria with substrates, elevating reactive oxygen species and inducing systemic stress.',
        'reason_ur' => 'جسمانی توانائی کی ضرورت سے زیادہ کھانا مائٹوکونڈریا پر بوجھ ڈالتا ہے جس سے ری ایکٹو آکسیجن پیدا ہوتی ہے اور نظامی تناؤ بڑھتا ہے۔',
        'avoid_en' => ['Fried Foods', 'Carbonated Drinks', 'Trans Fats', 'Simple Carbohydrates'],
        'avoid_ur' => ['تلی ہوئی چیزیں', 'کاربونیٹیڈ ڈرنکس', 'ٹرانس فیٹس', 'سادہ کاربوہائیڈریٹس'],
        'control_en' => ['Incorporate high-fiber complex carbohydrates', 'Adhere to portion control standards', 'Avoid eating late-night heavy meals'],
        'control_ur' => ['زیادہ فائبر والے پیچیدہ کاربوہائیڈریٹس شامل کریں', 'پورشن کنٹرول کے اصولوں پر عمل کریں', 'رات گئے بھاری کھانا کھانے سے پرہیز کریں']
    ],
    [
        'id' => 'gerd',
        'title_en' => 'Heartburn / GERD',
        'title_ur' => 'سینے کی جلن / تیزابیت',
        'target_kcal' => 1300,
        'tag' => 'Gastroenterology',
        'description_en' => 'Acid reflux caused by low lower esophageal sphincter tone or high abdominal pressure, exacerbated by large or fatty meals.',
        'description_ur' => 'معدے کے تیزاب کا اوپر کی طرف بہاؤ جو نچلے غذائی نالی کے پٹھے کی کمزوری یا پیٹ کے زیادہ دباؤ کی وجہ سے ہوتا ہے، جو بڑے یا چکنائی والے کھانوں سے بڑھ جاتا ہے۔',
        'reason_en' => 'Large meals increase intra-abdominal pressure and delay gastric emptying, forcing stomach acid up into the sensitive esophageal lining.',
        'reason_ur' => 'زیادہ مقدار میں کھانا پیٹ کے دباؤ کو بڑھاتا ہے اور معدے کے خالی ہونے کے عمل کو سست کرتا ہے جس سے تیزاب اوپر کی طرف جاتا ہے۔',
        'avoid_en' => ['Spicy Foods', 'Citrus Fruits', 'Caffeine and Chocolate', 'Peppermint'],
        'avoid_ur' => ['مصالحہ دار کھانے', 'کھٹے پھل', 'کیفین اور چاکلیٹ', 'پودینہ'],
        'control_en' => ['Keep upright for 3 hours post-meal', 'Eat smaller portions divided into 5 meals', 'Stop eating at least 4 hours before bedtime'],
        'control_ur' => ['کھانے کے بعد 3 گھنٹے تک سیدھے بیٹھیں', 'بڑے کھانے کے بجائے 5 چھوٹے حصوں میں تقسیم کریں', 'سونے سے کم از کم 4 گھنٹے پہلے کھانا بند کر دیں']
    ],
    [
        'id' => 'bloating',
        'title_en' => 'Bloating',
        'title_ur' => 'پیٹ کا پھولنا',
        'target_kcal' => 1400,
        'tag' => 'Gastroenterology',
        'description_en' => 'Excessive accumulation of gas in the digestive tract due to fermentation of undigested foods, poor enzyme production, or dysbiosis.',
        'description_ur' => 'ہضم نہ ہونے والی غذاؤں کے سڑنے، انزائمز کی کم پیداوار، یا آنتوں کے جراثیم کی خرابی کی وجہ سے ہاضمے میں گیس کا زیادہ جمع ہونا۔',
        'reason_en' => 'Swallowing excess air during rushed eating and eating highly fermentable FODMAPs causes severe intestinal distension.',
        'reason_ur' => 'جلدی میں کھانا کھانے کے دوران ضرورت سے زیادہ ہوا نگلنا اور خمیر پیدا کرنے والی چیزیں کھانا آنتوں کے پھولنے کا سبب بنتا ہے۔',
        'avoid_en' => ['Artificial Sweeteners', 'Cruciferous Vegetables', 'Legumes and Beans', 'Wheat Gluten'],
        'avoid_ur' => ['مصنوعی میٹھے', 'بند گوبھی اور پھول گوبھی', 'دالیں اور لوبیا', 'گندم کا گلوٹین'],
        'control_en' => ['Chew each bite 30 times thoroughly', 'Avoid carbonated liquids during meals', 'Incorporate ginger or peppermint tea'],
        'control_ur' => ['ہر نوالے کو اچھی طرح 30 بار چبائیں', 'کھانے کے دوران کاربونیٹیڈ مشروبات سے پرہیز کریں', 'ادرک یا پودینے کی چائے شامل کریں']
    ],
    [
        'id' => 'abdominal-discomfort',
        'title_en' => 'Abdominal Discomfort',
        'title_ur' => 'پیٹ کی تکلیف',
        'target_kcal' => 1300,
        'tag' => 'Gastroenterology',
        'description_en' => 'General irritation, mild cramping, or persistent ache within the digestive tract, indicating mucosal inflammation or motility dysfunction.',
        'description_ur' => 'نظام ہاضمہ کے اندر عام جلن، ہلکا درد یا مسلسل تکلیف، جو آنتوں کی سوزش یا حرکت پذیری کی خرابی کی نشاندہی کرتی ہے۔',
        'reason_en' => 'Consumption of irritating foodstuffs and heavy spices triggers hyperactive gut motility, resulting in painful muscular spasms.',
        'reason_ur' => 'خارش پیدا کرنے والی اشیائے خوردونوش اور تیز مصالحوں کا استعمال آنتوں کی حرکت کو تیز کرتا ہے جس کے نتیجے میں تکلیف دہ اینٹھن ہوتی ہے۔',
        'avoid_en' => ['Raw Spicy Chili', 'Processed Dairy', 'Extreme Cold Beverages', 'Deep Fried Foods'],
        'avoid_ur' => ['کچی تیز مرچ', 'پروسیسڈ ڈیری اشیاء', 'انتہائی ٹھنڈے مشروبات', 'گہرے تلے ہوئے کھانے'],
        'control_en' => ['Consume warm, cooked foods', 'Implement a temporary low-FODMAP diet', 'Sip warm fluids instead of cold water'],
        'control_ur' => ['گرم اور پکا ہوا کھانا کھائیں', 'عارضی طور پر ہلکی غذا کا استعمال کریں', 'ٹھنڈے پانی کے بجائے ہلکا گرم پانی پییں']
    ],
    [
        'id' => 'diabetes',
        'title_en' => 'Type 2 Diabetes',
        'title_ur' => 'ذیابیطس ٹائپ 2',
        'target_kcal' => 1200,
        'tag' => 'Diabetology & Endocrinology',
        'description_en' => 'A chronic condition characterized by high blood glucose levels resulting from systemic insulin resistance and progressive pancreatic beta-cell fatigue.',
        'description_ur' => 'ایک دائمی حالت جس میں انسولین کی مزاحمت اور لبلبے کے خلیوں کی تھکن کے نتیجے میں خون میں گلوکوز کی سطح بڑھ جاتی ہے۔',
        'reason_en' => 'Persistent carbohydrate overload forces continuous insulin spikes, exhausting receptors and triggering chronic hyperglycemia.',
        'reason_ur' => 'نشاستہ دار غذاؤں کا مسلسل زیادہ استعمال انسولین کی سطح کو مستقل طور پر بڑھاتا ہے جس سے خلیات انسولین کے عادی ہو جاتے ہیں۔',
        'avoid_en' => ['Refined White Flour', 'Sugary Desserts', 'High Glycemic Fruits', 'Packaged Fruit Juices'],
        'avoid_ur' => ['ریفائنڈ سفید میدہ', 'میٹھی اشیاء', 'زیادہ شوگر والے پھل', 'ڈبے والے جوس'],
        'control_en' => ['Utilize strict carbohydrate portion counting', 'Engage in a 15-minute post-meal brisk walk', 'Prioritize high-fiber complex greens'],
        'control_ur' => ['نشاستہ دار غذاؤں کی پیمائش کریں', 'کھانے کے بعد 15 منٹ تیز چہل قدمی کریں', 'زیادہ فائبر والی ہری سبزیوں کو ترجیح دیں']
    ],
    [
        'id' => 'hypertension',
        'title_en' => 'Hypertension',
        'title_ur' => 'ہائی بلڈ پریشر',
        'target_kcal' => 1400,
        'tag' => 'Cardiology',
        'description_en' => 'Chronic elevation of systemic arterial blood pressure, placing severe workload strain on the vascular network and cardiac tissue.',
        'description_ur' => 'شریانوں کے خون کے دباؤ میں مسلسل اضافہ، جو خون کی نالیوں اور دل پر شدید بوجھ اور دباؤ ڈالتا ہے۔',
        'reason_en' => 'High sodium intake increases blood volume, while arterial stiffness caused by metabolic inflammation elevates systemic resistance.',
        'reason_ur' => 'نمک کا زیادہ استعمال خون کے حجم کو بڑھاتا ہے، جبکہ میٹابولک سوزش کی وجہ سے شریانوں کی سختی دباؤ میں اضافہ کرتی ہے۔',
        'avoid_en' => ['Table Salt', 'Cured or Salted Meats', 'Pickles and Soy Sauce', 'Canned Soups'],
        'avoid_ur' => ['عام خوردنی نمک', 'نمکین یا خشک کیا ہوا گوشت', 'اچار اور سویا ساس', 'ڈبے والے سوپ'],
        'control_en' => ['Adopt the DASH eating pattern rules', 'Strictly limit daily sodium to 1500mg', 'Increase natural potassium via leafy greens'],
        'control_ur' => ['ڈیش (DASH) غذا کے اصولوں کو اپنائیں', 'روزانہ سوڈیم کی مقدار 1500 ملی گرام تک محدود کریں', 'پتوں والی سبزیوں سے پوٹاشیم حاصل کریں']
    ],
    [
        'id' => 'high-cholesterol',
        'title_en' => 'High Cholesterol',
        'title_ur' => 'کولیسٹرول کی زیادتی',
        'target_kcal' => 1300,
        'tag' => 'Cardiology & Lipidology',
        'description_en' => 'Elevated circulating levels of low-density lipoprotein (LDL) and total cholesterol, causing plaque buildup in arterial structures.',
        'description_ur' => 'خون میں ایل ڈی ایل (برا کولیسٹرول) اور کل کولیسٹرول کی بڑھتی ہوئی سطح، جو شریانوں میں چربی کے جمنے کا سبب بنتی ہے۔',
        'reason_en' => 'High intake of saturated and trans fats down-regulates hepatic LDL receptors, trapping cholesterol in general circulation.',
        'reason_ur' => 'سیچوریٹڈ اور ٹرانس فیٹس کا زیادہ استعمال جگر کے کولیسٹرول جذب کرنے والے ریسیپٹرز کو کمزور کرتا ہے جس سے یہ خون میں پھنس جاتا ہے۔',
        'avoid_en' => ['Butter and Ghee', 'Organ Meats', 'Full-Fat Dairy Products', 'Processed Bakery Goods'],
        'avoid_ur' => ['مکھن اور گھی', 'کلیجی اور مغز', 'ملائی والا دودھ اور دہی', 'بیکری کی مصنوعات'],
        'control_en' => ['Incorporate soluble fiber from oats/barley', 'Limit saturated fat to under 10g per day', 'Use heart-healthy monounsaturated fats'],
        'control_ur' => ['جئی اور جو سے حل پذیر فائبر شامل کریں', 'سیچوریٹڈ چربی کو روزانہ 10 گرام سے کم رکھیں', 'دل کے لیے مفید مونو انسیچوریٹڈ چربی کا استعمال کریں']
    ],
    [
        'id' => 'fatty-liver',
        'title_en' => 'Fatty Liver Disease',
        'title_ur' => 'جگر پر چربی',
        'target_kcal' => 1200,
        'tag' => 'Hepatology',
        'description_en' => 'Pathological accumulation of triglycerides inside hepatocytes, causing inflammatory stress and potential progressive fibrosis.',
        'description_ur' => 'جگر کے خلیوں کے اندر چربی کا غیر معمولی جمع ہونا، جو سوزش اور جگر کے مستقل نقصان کا باعث بن سکتا ہے۔',
        'reason_en' => 'Excessive consumption of high-fructose corn syrup and simple sugars triggers hepatic de novo lipogenesis, coating liver tissue.',
        'reason_ur' => 'چینی اور ہائی فرکٹوز شربت کا زیادہ استعمال جگر میں چربی بنانے کے عمل کو متحرک کرتا ہے، جس سے جگر پر چربی چڑھتی ہے۔',
        'avoid_en' => ['High Fructose Corn Syrup', 'Sweets and Pastries', 'White Rice and Bread', 'Deep Fried Snacks'],
        'avoid_ur' => ['فرکٹوز والا شربت', 'مٹھائیاں اور پیسٹری', 'سفید چاول اور ڈبل روٹی', 'گہرے تلے ہوئے سنیکس'],
        'control_en' => ['Engage in carbohydrate restriction', 'Ensure a minimal 12-hour overnight fast', 'Include antioxidant-rich leafy greens daily'],
        'control_ur' => ['نشاستہ دار غذاؤں کو محدود کریں', 'رات بھر کم از کم 12 گھنٹے کا روزہ رکھیں', 'روزانہ اینٹی آکسیڈینٹ سے بھرپور سبزیاں کھائیں']
    ],
    [
        'id' => 'weight-gain',
        'title_en' => 'Weight Gain',
        'title_ur' => 'وزن کا بڑھنا',
        'target_kcal' => 1400,
        'tag' => 'Bariatrics & Metabolism',
        'description_en' => 'Accumulation of adipose tissue due to positive energy balance, hormonal dysregulation, or low metabolic rate.',
        'description_ur' => 'زیادہ کیلوریز کے استعمال، ہارمونز کی خرابی یا سست میٹابولزم کی وجہ سے جسم میں اضافی چربی کا جمع ہونا۔',
        'reason_en' => 'Overeating energy-dense, low-nutrient foods leads to chronic fat storage and insulin resistance.',
        'reason_ur' => 'غذائیت سے خالی لیکن کیلوریز سے بھرپور کھانے زیادہ کھانے سے چربی ذخیرہ ہوتی ہے اور انسولین کی مزاحمت ہوتی ہے۔',
        'avoid_en' => ['Sugary Beverages', 'Heavy Fast Food', 'Late Night Sweets', 'Refined Cereals'],
        'avoid_ur' => ['میٹھے مشروبات', 'بھاری فاسٹ فوڈ', 'رات گئے میٹھی چیزیں', 'ریفائنڈ اناج'],
        'control_en' => ['Maintain a 500 kcal energy deficit', 'Keep a daily food and calorie journal', 'Eat meals slowly to let leptin activate'],
        'control_ur' => ['روزانہ 500 کیلوریز کی کمی برقرار رکھیں', 'روزانہ کھانے کی اشیاء کا ریکارڈ رکھیں', 'ہلکا چبا کر کھائیں تاکہ تسکین کا احساس ہو']
    ],
    [
        'id' => 'obesity',
        'title_en' => 'Obesity',
        'title_ur' => 'موٹاپا',
        'target_kcal' => 1200,
        'tag' => 'Bariatrics & Endocrinology',
        'description_en' => 'A complex, chronic metabolic disease marked by excessive visceral fat deposits that impair vascular, cardiac, and endocrine functions.',
        'description_ur' => 'ایک پیچیدہ اور دائمی میٹابولک بیماری جس میں اندرونی اعضاء کے گرد اضافی چربی دل اور ہارمونز کے کام کو متاثر کرتی ہے۔',
        'reason_en' => 'Leptin resistance coupled with high-calorie density foods overrides natural satiety signaling, encouraging chronic overeating.',
        'reason_ur' => 'پیٹ بھرنے کے سگنل دینے والے ہارمون کی مزاحمت اور زیادہ کیلوریز والے کھانے پیٹ بھرنے کا احساس ختم کر کے زیادہ کھانے پر مجبور کرتے ہیں۔',
        'avoid_en' => ['Ultra-Processed Foods', 'Sweetened Desserts', 'Deep Fried Carbohydrates', 'Sweetened Dairy'],
        'avoid_ur' => ['انتہائی پروسیسڈ غذائیں', 'میٹھے پکوان', 'گہری تلی ہوئی نشاستہ دار اشیاء', 'میٹھی ڈیری'],
        'control_en' => ['Limit eating windows to 8 hours daily', 'Base meals strictly around lean proteins', 'Exercise at moderate intensity 150 min/week'],
        'control_ur' => ['کھانے کے اوقات کو روزانہ 8 گھنٹے تک محدود کریں', 'کم چربی والے پروٹین کو ترجیح دیں', 'ہفتے میں 150 منٹ درمیانی ورزش کریں']
    ],
    [
        'id' => 'heart-disease',
        'title_en' => 'Heart Disease',
        'title_ur' => 'دل کا عارضہ',
        'target_kcal' => 1400,
        'tag' => 'Cardiology',
        'description_en' => 'Structural or functional disorders of cardiac tissues and coronary arteries, typically caused by plaque or chronic inflammation.',
        'description_ur' => 'دل کے پٹھوں اور شریانوں کے کام میں خرابی، جو عام طور پر چربی جمنے یا دائمی سوزش کی وجہ سے ہوتی ہے۔',
        'reason_en' => 'Consuming processed trans fats and high sodium spikes systemic inflammation and blood pressure, damaging vascular linings.',
        'reason_ur' => 'پروسیسڈ ٹرانس فیٹس اور زیادہ نمک کا استعمال سوزش اور بلڈ پریشر کو بڑھاتا ہے، جس سے دل کی نالیوں کو نقصان پہنچتا ہے۔',
        'avoid_en' => ['Processed Trans Fats', 'Excessive Table Salt', 'High Fat Red Meat', 'Sugary Confectioneries'],
        'avoid_ur' => ['پروسیسڈ ٹرانس فیٹس', 'خوردنی نمک کی زیادتی', 'زیادہ چربی والا بڑا گوشت', 'میٹھی چیزیں'],
        'control_en' => ['Adhere strictly to the heart-healthy Mediterranean diet', 'Take Omega-3 fatty acid food sources', 'Restrict daily sodium intake below 1500mg'],
        'control_ur' => ['بحیرہ روم کی دل دوست غذا پر سختی سے عمل کریں', 'اومیگا تھری فیٹی ایسڈ والی اشیاء کھائیں', 'روزانہ سوڈیم 1500 ملی گرام سے کم رکھیں']
    ]
];
